### ISSUE TITLE
非 HttpContext 时，如果使用者自己创建了一个 scope 那么目前文档中没有相关实现说明。

### ISSUE THREAD

**Issue by hzy-6** [inversionhourglass/Rougamo.DI#1]
肉夹馍应该从实现类构造中拿到一个 IServiceProvider 才对

**Comment by inversionhourglass** [comment]
是指在AspNetCore项目中当前无`HttpContext`的情况吗，比如在`HostedService`中？这种可以参考 [非httpcontext-scope](https://github.com/inversionhourglass/Rougamo.DI?tab=readme-ov-file#%E9%9D%9Ehttpcontext-scope) 部分的说明

```csharp
public static void Main(string[] args)
{
    var builder = WebApplication.CreateBuilder(args);
    // ...省略其他步骤
    builder.Services.AddNestableHttpContextScopeAccessor();  // 额外的注册步骤
    builder.Services.AddRougamoAspNetCore();
    // ...省略其他步骤
}

public class Cls(IServiceProvider services)
{
    public void M()
    {
        // 调用扩展方法CreateResolvableScope创建scope，这里如果使用CreateScope来创建，那么这个scope将无法在切面类型中获取到
        using var scope = services.CreateResolvableScope();
    }
}
```

另外关于你说的
> 肉夹馍应该从实现类构造中拿到一个 IServiceProvider 才对

你说的这个就假定了两点，但是这两点我都无法假定：
1. 当前类的构造方法一定会传入`IServiceProvider`；
2. 当前肉夹馍应用的方法是实例方法而非静态方法。

**Comment by hzy-6** [comment]
<img width="1066" alt="image" src="https://github.com/user-attachments/assets/c74bbcc4-d388-417c-8c6b-a8fcf2743b08">
这种定时任务出发的 class ，那么在调用时我会手动创建一个 scope 然后对类做反射 var jobTaskObject = ActivatorUtilities.CreateInstance(serviceProvider, jobTaskInfo.ClassType);// di 创建服务 这种。拦截器中不知道能不能取到我创建的 scope 然后在去拿 IServiceProvider

**Comment by inversionhourglass** [comment]
场景是支持的，不过我看你调用的是`IServiceScopeFactory.CreateAsyncScope`方法，这个版本忘记提供async scope对应的方法了，如果你这个scope里没有实现`IAsyncDisposable`的类型，可以改用`IServiceProvider.CreateResolvableScope`方法。

最近在更改实现方式，下个版本应该就能直接支持原生的`CreateScope`和`CreateAsyncScope`了

**Comment by hzy-6** [comment]
不是这样的，我的类是通过反射创建的，如果aop拦截只能从构造拿到 scope 。反射构建时，我通过构造传递的 IServiceProvider

**Comment by inversionhourglass** [comment]
没明白，你哪个类是通过反射创建的。

以你截图的代码为例，`_serviceScopeFactory`肯定不是反射创建的吧，`_serviceScopeFactory.CreateAsyncScope()`改成`_serviceProvider.CreateResolvableScope()`应该不存在阻碍吧。如果上面的这不操作没有问题，那么后续在这个scope范围内，无论你是通过scope从IoC/DI容器中获取的实例，还是反射创建的实例，再或者是直接手动new创建的实例，都能正确获取到`IServiceProvider`，创建实例的时候也不需要你通过构造方法传递`IServiceProvider`。

如果还有疑问，你最好提供一个完整的简单实例代码，现在沟通起来有点盲人摸象了。

**Comment by inversionhourglass** [comment]
> 最近在更改实现方式，下个版本应该就能直接支持原生的CreateScope和CreateAsyncScope了

已完成我之前说的功能，现在对你之前给出的代码场景应该更适配，可以参考 https://www.cnblogs.com/nigture/p/18412772#%E8%82%89%E5%A4%B9%E9%A6%8D%E7%9B%B8%E5%85%B3%E5%BA%94%E7%94%A8 ，或者直接参考示例项目 https://github.com/inversionhourglass/Rougamo.DI/tree/master/samples

先关闭该issue，如果还有问题再重新打开。
